apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-deployment
  namespace: work
  labels:
    app.kubernetes.io/name: &app nginx
    app.kubernetes.io/version: &version 1.27.5
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: *app
      app.kubernetes.io/version: *version
  template:
    metadata:
      labels:
        app.kubernetes.io/name: *app
        app.kubernetes.io/version: *version
    spec:
      initContainers:
        - name: init-myservice
          image: busybox:1.28
          command: 
            - 'sh'
            - '-c'
            - 'echo Initializing... && sleep 10'
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      containers:
        - name: nginx
          image: nginx:1.27.5
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
