---
apiVersion: v1
kind: Service
metadata:
  name: my-first-nginx
  namespace: work
  labels:
   app.kubernetes.io/name: nginx
   app.kubernetes.io/version: 1.27.5
spec:
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: 1.27.5
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
